examples/streamlit_app.py, streamlit_folium/__init__.py
Streamlit-folium component now supports also [DualMap](https://python-visualization.github.io/folium/plugins.html#folium.plugins.DualMap) from Folium plugins.
* Add switch in streamlit-folium `__init__.py` to properly handle DualMap rendering
* Update app example adding DualMap
=> Add DualMap support

.gitignore, examples/draw_support.py, setup.py, streamlit_folium/__init__.py, streamlit_folium/frontend/package.json, streamlit_folium/frontend/public/index.html, streamlit_folium/frontend/src/index.tsx
This adds two new entries to the exported json -- all_drawings and latest_active_drawing (either clicked or drawn).
=> Add support for getting all drawn objects on the map

streamlit_folium/frontend/public/index.html
Apparently Safari is unhappy with rendering an empty iframe, even if that iframe eventually gets populated, which is why with draw(export=True) it works, because it adds a single link below the map with "Export". This adds a single space to the bottom, and it works. Probably going to mess up your pixel tests again :)
=> Fix safari

setup.py, streamlit_folium/__init__.py
This is specifically to handle https://github.com/python-visualization/folium/issues/1599, which may get fixed eventually, but since this is just providing a sensible initial value, it doesn't seem too critical if there are edge cases where it ends up with Nones (which is the behavior you would get if you put an empty map).
=> Dont fail on bounds

examples/requirements.txt
The example app is still running 0.6.9, and so failing
=> Force the example app to use the latest release

setup.py, streamlit_folium/__init__.py, streamlit_folium/frontend/src/index.tsx
This makes the javascript code generated for both the original map and the updates to be deterministic, by overriding the assigned `_id` values.
=> Standardize ids that get assigned to force unnecessary rerunning, and explicitly turn off events for old layers

setup.py, streamlit_folium/frontend/public/index.html
Fixes #79 (hopefully)
I experienced the issue reported by @mcarlosfr when trying to load the js for that package, and the jsdelivr version seemed to load much faster. So, I went ahead and switched out all of the unpckg links for jsdelivr.
I created #115 to make a more long-term solution eventually.
=> Move to jsdeliver

.github/workflows/run_tests_each_PR.yml, .gitignore, examples/pages/misc_examples.py, setup.py, streamlit_folium/__init__.py, tests/requirements.txt, tests/test_frontend.py
This change will significantly improve the running time of `st_folium` on maps with many children.
In an example I tried with 10,336 child objects, the running time was improved from ~14 seconds to ~400 milliseconds.
Fixes #125
=> Improve performance on maps with many children

streamlit_folium/__init__.py
This PR fixes https://github.com/randyzwitch/streamlit-folium/issues/143
-> fig.render is removed in _get_map_string and _get_siblings to avoid redundancy.
Note : performance gain to have the map depicted on my use case (with st.profiler) : from 40sec to 25sec. (almost 40%)
=> Use render() in main only once

.github/workflows/publish_PYPI_each_tag.yml, .github/workflows/run_tests_each_PR.yml, requirements.txt, setup.py, streamlit_folium/frontend/package.json, tests/requirements.txt
This fix https://github.com/randyzwitch/streamlit-folium/issues/127
The main blocker was streamlit-component-lib not upgrading to v2
=> bump node to current LTS & adapt build accordingly

examples/pages/grouped_layer_control.py, setup.py, streamlit_folium/frontend/public/index.html, tests/test_frontend.py
=> Support grouped layer control

streamlit_folium/frontend/public/index.html
=> Remove duplicate jquery, update to latest

requirements.txt, setup.py, tests/requirements.txt, tests/test_package.py
If I'm thinking about this correctly @blackary, we don't need to exclude 0.15.0 per se, since the solver should always go to the patch version. Thus, we can keep the requirements much looser.
If you disagree, then make a commit here. Otherwise, we'll put out a new version of streamlit-folium as well.
References #148
=> Allow v0.15.1 of Folium

streamlit_folium/frontend/public/index.html
Update vega/vega-lite to use the "5.x" series of updates.
Fixes #158
=> Update vega libraries

examples/pages/dynamic_updates.py, streamlit_folium/__init__.py, streamlit_folium/frontend/src/index.tsx, tests/test_frontend.py, tests/test_package.py
It gives the ability to provide feature groups as list
It fixes #163 and (includes #164)
I added tests to make sure it works. 
@blackary I am not an expert with this testing library, so I used the styling to make sure the layer is shown or not. There is probably a better way of doing it.
It partially addresses #153 (possibility to pass a list of feature groups). 
However, the layerControl is still not available.
=> Ability to provide feature group as list

.gitignore, examples/pages/image_overlay.py, streamlit_folium/__init__.py, streamlit_folium/frontend/src/index.tsx
Added way to ensure image pixelated style because st_folium was not rendering the styles set with folium.ImageOverlay(..., pixelated=True) making images blurrier, which sometimes is not desirable.
I had this issue and there was another person on streamlit community forum that also noted this behavior [link to post](https://discuss.streamlit.io/t/image-visualization-blurred-pixels-in-st-folium-vs-crisp-in-folium-static/61213).
I would like to help on this topic with this pull request, so if you guys think this is good for the project I am willing to fulfill any changes that are needed for the merge, and excuse me if I did anything out of pattern, I am new to contributing and willing to learn by doing.
=> pixelated images when needed

streamlit_folium/frontend/public/index.html
Closes #174.
I am a contributing developer of Folium and the developer of the Folium realtime plugin. Great work on streamlit-folium! I use Folium mainly from streamlit, so your package is really useful to me.
To fix the issue I added a link to the javascript file for realtime plugin to the component's public/index.html. I am curious though if streamlit-folium could not be changed to generate these links based on the Folium generated map. We are updating the Folium code base so that users can and and override javascript and css files at runtime. This would break the currently hardcoded list of javascript and css links. 
The Folium generated code contains links to include the required javascript and css files. Is there some way these could be included in the generated code?
=> Added link to JS for realtime

.github/workflows/run_tests_each_PR.yml, tests/requirements.txt
It breaks the automated tests.
The test_package.py and test_release.py fail with error message: "RuntimeError: Runtime hasn't been created!"
Reverting to Streamlit 1.33 solved the issue.
=> Exclude streamlit version 1.34 from requirements

.github/workflows/run_tests_each_PR.yml, README.md, examples/pages/realtime.py
Re-opened. The issue with the tests is on the streamlit side and not with this example.
Closes #184 
@randyzwitch can you have a look?
=> Add realtime example

streamlit_folium/__init__.py, streamlit_folium/frontend/src/index.tsx
This PR addresses several issues related to dynamic JavaScript packages imports and the not displayed colormap.
1. JavaScript package loading order
The script loading mechanism in `index.tsx` has been modified to ensure that JavaScript packages are imported sequentially. This should fix the issues with the vanishing overlay and feature groups caused by dependencies not being loaded in the correct order.
2. Colormap display
The `d3` package, required for displaying the `colormap`, has been manually included. The previous dynamic JS and CSS dependency detection in `__init__.py` did not work for `branca.colormap.ColorMap` objects, leading to the colormap not being displayed.
With these changes, the dynamic package loading and colormap display issues should be resolved.
=> Fix dynamic JS import and add missing scripts for colormaps

streamlit_folium/__init__.py
Permits caching of the rendering which for scenarios where the same maps are shown can increase performance
closes #194
=> Make rendering optional

setup.py, streamlit_folium/__init__.py, tests/test_frontend.py
* Ignore elements where there is no special css or js to load
* Add test to check for regression on geojson popup
* Fix selectors for a few tests
* Bump version to 0.21.1
Fixes #200 
Fixes #199
=> Fix error where default_css was missing

streamlit_folium/frontend/public/index.html
As per #204 - this fixes the issue of 7.5px font sizes in map elements.
In local testing, the issue was still present, but was coming from bootstrap.min.css rather than glyphicon-boostrap.css but the effect was the same. I don't think this fix will cause other issues as it is only setting the iframe font-size to 1rem, which should be a pretty safe default.
=> add font-size to html tag to avoid conflict with bootstrap css

streamlit_folium/__init__.py
In some cases folium generates an id for the draw control that ends in a different digit. Not sure when or why.
This change uses a regex to rename drawnItems_<suffix> to drawnItems in javascript, so it can handle both cases.
Closes issue #203
=>  Fix issue with Draw Support

README.md
Hi Randy,
I think it would be nice if people can play directly with your library on https://py.cafe
I don't know if you like that the link to the project links to a personal project of mine.
If something needs to change, you can always fork it, edit it and point to your project.
Let me know what you think.
Regards,
Maarten
Including the markdown below so you can preview it:
---
[<img src="https://py.cafe/logos/pycafe_logo.png" alt="PyCafe logo" width="24" height="24"> Run and edit this example in Py.Cafe](https://py.cafe/maartenbreddels/streamlit-folium-geospatial-visualizations)
=> docs: include link to PyCafe for a live example

examples/pages/layer_control.py, streamlit_folium/__init__.py, streamlit_folium/frontend/src/index.tsx
**Description:**
I primarily use st_folium in combination with LayerControl in Streamlit applications. However, one challenge I encountered is that there is no straightforward way to determine which layers are currently selected from the LayerControl. This limits functionality when trying to dynamically update components such as legends for each layer.
**Here's a basic example of the issue:**
- The user toggles visibility of multiple layers using LayerControl.
- There is no direct support to return the currently selected layers, which makes it difficult to update elements like legends that correspond to those layers.
To address this issue, I introduced a modification that allows st_folium to return the currently selected layers when interacting with the LayerControl. Now, when users …
=> Add return values for selected layers in LayersControl

README.md, examples/pages/layer_control.py, streamlit_folium/__init__.py, streamlit_folium/frontend/src/index.tsx
This Pullrequest is the response to this pull request
[Pull Request](https://github.com/randyzwitch/streamlit-folium/pull/217)
I think I found the issue why one test hasnt passed. I rerun the tests locally and all of them have passed.
Sorry for the inconvenicence so far. 
**Description:**
I primarily use st_folium in combination with LayerControl in Streamlit applications. However, one challenge I encountered is that there is no straightforward way to determine which layers are currently selected from the LayerControl. This limits functionality when trying to dynamically update components such as legends for each layer.
**Here's a basic example of the issue:**
The user toggles visibility of multiple layers using LayerControl.
There is no direct support to return the currently selected …
=> Returning selected layers

setup.py
Moving it up another minor version since we dropped 3.8 from the test matrix. So updated the version number and changed `python_requires`
=> Prepare for 0.23.0 release

streamlit_folium/frontend/src/index.tsx
I noticed the `Streamlit.setComponentValue()` example (in `realtime.py`) was no longer working. For some reason, in the latest releases the Streamlit library is no longer in the global namespace. This change adds it back to the window namespace, so JsCode callbacks in Folium can return values to Streamlit.
Closes #231
=> Add a global reference to the Streamlit library

streamlit_folium/frontend/src/index.tsx, tests/test_frontend.py
Might be related to #213
It looks like the `setFrameHeight` behavior broke between versions `0.20.0` and `0.20.1` leading to too much bottom space after a map. If you take for example this app: https://github.com/danielan987/datafarm, you can see that the Selectbox element is way too far in the bottom when using a version > `0.20.0` but still works in `0.20.0`. 
The proposed fix here seems to resolve the issue. I also added an e2e test to ensure that the `iframe` height and the inner `html` height match.
=> Call Streamlit.setFrameHeight to set frame height correctly

setup.py
While running [liccheck](https://pypi.org/project/liccheck/) streamlit-folium is flagged as an 'unknown' license. I believe this can be solved by adding the license type into setup.py. An example of this can be seen at the [folium repo](https://github.com/python-visualization/folium/blob/main/setup.py) .
Thank you for a great package!
=> add license detail to setup.py

examples/pages/geojson_popup.py, examples/pages/layer_control.py, examples/pages/simple_popup.py
Imports should be from `folium` or `folium.plugins` to avoid problems if folium ever refactors its inner package structure.
=> Cleanup examples

streamlit_folium/frontend/src/index.tsx
Simple fix, add a try catch around retrieving the popup text. 
I was unable to figure out *why* this error occurs. It seems the Drawn layers somehow look like they have a popup content without having the corresponding getPopup() method.
=> Fixes #264
