- setup.py
- streamlit_folium/frontend/public/index.html
- streamlit_folium/frontend/src/index.tsx
Fixes #34 by adding some missing js dependencies.
> Fix-bidirectional

- setup.py
- streamlit_folium/frontend/src/index.tsx
> Get map zoom

- requirements.txt
- setup.py
- streamlit_folium/__init__.py
> Fix popups and default return

- streamlit_folium/__init__.py
- streamlit_folium/frontend/src/circle-to-polygon.tsx
- streamlit_folium/frontend/src/index.tsx
> Add last drawn circle radius and polygon to output

- setup.py
- streamlit_folium/__init__.py
- streamlit_folium/frontend/src/index.tsx
> Support html siblings to the map

- streamlit_folium/frontend/public/index.html
- streamlit_folium/frontend/src/index.tsx
> Shrink second pane unless using it for DualMap

- examples/pages/draw_support.py
- examples/pages/limit_data_return.py
- examples/pages/misc_examples.py
- streamlit_folium/__init__.py
- tests/test_package.py
> Fix bug, isolate string generation, add more tests

- streamlit_folium/__init__.py
- streamlit_folium/frontend/src/index.tsx
- tests/test_frontend.py
> Add support for last tooltip clicked and add test

- requirements.txt
- setup.py
- streamlit_folium/frontend/public/index.html
> Bump minimum streamlit version

- .github/workflows/publish_PYPI_each_tag.yml
- .github/workflows/run_tests_each_PR.yml
- examples/requirements.txt
Was having an issue that I think is related to an old version of node, so I also bumped actions version to hopefully resolve #118
> I found the same issue with an unpkg library taking a long time to load

- .github/workflows/publish_PYPI_each_tag.yml
Pin node version to ensure same build environment between tests and PyPI build
> Pin to node 16 in PyPI script

- examples/pages/simple_popup.py
- streamlit_folium/__init__.py
- streamlit_folium/frontend/src/index.tsx
- tests/test_frontend.py
Pulled the popup & hover stuff out of https://github.com/randyzwitch/streamlit-folium/pull/131 to separate it out from the linting.
> Add popup return and return_on_hover

- .github/workflows/run_tests_each_PR.yml
- setup.py
> Update Python versions tested

- setup.py
- streamlit_folium/frontend/public/index.html
Fixes #158, for real this time
> Add vega embed

- setup.py
- streamlit_folium/__init__.py
- streamlit_folium/frontend/src/index.tsx
- tests/test_frontend.py
- tests/test_package.py
The changes to support 0.15.1 #156 unintentionally broke the drawing feature
This fixes that, and adds a better test of the drawing functionality
Thanks @this-josh for catching this issue!
Fixes #161
> Fix draw support for folium >= 0.15

- .github/workflows/run_tests_each_PR.yml
> Add Python 3.12 to test harness

- .pre-commit-config.yaml
- pyproject.toml
Should fix the problem blocking #211 
The main issue is that types-all is no longer working
> All ruff, upgrade, remove types-all

- examples/pages/dynamic_updates.py
> Remove experimental_ prefix from example app

- examples/pages/geojson_popup.py
Fixes #220 
The remaining errors about protobufs I assume are from base Streamlit, which would handle that on its own
> Fix FutureWarning about literal json

- .github/workflows/linting.yml
- .github/workflows/run_tests_each_PR.yml
Related to https://github.com/pre-commit/action/issues/210
> Should fix the lint action failing

- tests/test_frontend.py
> Just go ahead and drop flaky test

- streamlit_folium/frontend/src/index.tsx
- tests/test_frontend.py
I ran the provided test script from the issue against the new code. As an extra check I also increased the provided height a few times, and I also ran without providing an explicit height variable. They all seem to work fine.
> Use the provided height explicitly
